name: Update Config

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # هر روز ساعت 01:00 UTC

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp pyyaml

      - name: Run fetch_and_convert.py
        run: python fetch_and_convert.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add config.yaml
          git commit -m "Auto update config.yaml" || echo "No changes to commit"
          git push
