name: Filter Subs and Upload to زخخخخسس

on:
  schedule:
    - cron: '0 */6 * * *'  # اجرای خودکار هر ۶ ساعت
  workflow_dispatch:       # امکان اجرای دستی هم وجود داره

jobs:
  filter-subs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml aiohttp requests

      - name: Run filter script
        run: python filter_subs.py

      - name: Upload to Gist
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: |
          echo "Uploading best_sub.yaml to Gist..."
          ESCAPED_CONTENT=$(jq -Rs . < best_sub.yaml)
          curl -X PATCH "https://api.github.com/gists/$GIST_ID" \
            -H "Authorization: Bearer $GIST_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"files\": {\"best_sub.yaml\": {\"content\": $ESCAPED_CONTENT}}}"
