name: Filter Subs & Upload

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: pip install pyyaml aiohttp

      - run: python filter_subs.py

      - name: Upload config.yaml to Gist
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: |
          CONTENT=$(python3 -c "import json; print(json.dumps(open('config.yaml').read()))")
          echo "{\"files\": {\"config.yaml\": {\"content\": $CONTENT}}}" > payload.json
          curl -X PATCH "https://api.github.com/gists/$GIST_ID" \
            -H "Authorization: Bearer $GIST_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d @payload.json
