name: Filter Subs and Upload to Gist

on:
  schedule:
    - cron: '0 */6 * * *'  # اجرا هر 6 ساعت
  workflow_dispatch:       # امکان اجرا دستی

jobs:
  filter-subs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml aiohttp requests

      - name: Run filter script
        run: python filter_subs.py

      - name: Upload to Gist
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: |
          echo "Preparing JSON payload with Python escaping..."

          CONTENT=$(python3 -c "import json; print(json.dumps(open('best_sub.yaml').read()))")
          echo "{\"files\": {\"best_sub.yaml\": {\"content\": $CONTENT}}}" > payload.json

          echo "Uploading best_sub.yaml to Gist..."
          curl -X PATCH "https://api.github.com/gists/$GIST_ID" \
            -H "Authorization: Bearer $GIST_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d @payload.json
