name: Update Subs Filter

on:
  schedule:
    - cron: '0 */6 * * *'   # هر ۶ ساعت اجرا می‌شود
  workflow_dispatch:         # اجازه اجرای دستی از UI

jobs:
  filter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml aiohttp

      - name: Run filter script
        run: python filter_subs.py

      - name: Upload filtered sub to Gist
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update filtered subscription
          file_pattern: best_sub.yaml

      - name: Create Gist with filtered subscription
        uses: devops-infra/action-gist@v2
        with:
          gist_id: ${{ secrets.GIST_ID }}
          filename: best_sub.yaml
          description: Filtered subscription updated by GitHub Actions
          public: true
          file: best_sub.yaml
