name: Update Subs Filter

on:
  schedule:
    - cron: '0 */6 * * *'   # هر ۶ ساعت
  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyyaml aiohttp

      - name: Run filter script
        run: python filter_subs.py

      - name: Upload to Gist
        run: |
          gist_id="6368a9e94efc6cbb8437e8598db92db8"
          filename="best_sub.yaml"
          desc="Updated filtered subs"
          curl -X PATCH "https://api.github.com/gists/$gist_id" \
            -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"description\": \"$desc\", \"files\": {\"$filename\": {\"content\": \"$(cat best_sub.yaml)\"}}}"
